# Generated by Django 4.1.7 on 2023-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.IntegerField(primary_key=True, serialize=False)),
                ("bio", models.TextField()),
                (
                    "profile_pic",
                    models.ImageField(
                        default="blank-profile-picture.png", upload_to="profile_images"
                    ),
                ),
            ],
        ),
    ]
