# Generated by Django 4.1.7 on 2023-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profile_birth_date_profile_location_profile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=0),
        ),
    ]
