# Generated by Django 4.1.7 on 2023-05-07 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_profile_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id_user",
        ),
    ]
