# Generated by Django 4.1.7 on 2023-05-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_profile_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
