# Generated by Django 4.1.7 on 2023-05-09 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_profile_birth_date_remove_profile_profile_pic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profileimg",
            new_name="profile_pic",
        ),
    ]
