# Generated by Django 4.1.7 on 2023-05-10 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_post_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
