# Generated by Django 4.1.7 on 2023-05-16 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
    ]
