# Generated by Django 4.1.7 on 2023-05-16 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_rename_comment_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
