# Generated by Django 4.1.7 on 2023-05-16 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_comment_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="profile",
        ),
    ]
